### ISSUE TITLE
ClojureScript

### ISSUE THREAD

**Issue by damassi** [AtomLinter/linter-clojure#16]
Would it be simple to modify this plugin to support ClojureScript as well?

**Comment by Arcanemagus** [comment]
Assuming the clojure.jar file supports it with the same options and the same output format it should be as simple as adding that to the list of supported scopes. Have you tried that locally?

**Comment by damassi** [comment]
@Arcanemagus - can you explain a little better what you mean? I'm very new to Clojure / ClojureScript development, though an experienced programmer

**Comment by Arcanemagus** [comment]
In [this block](https://github.com/AtomLinter/linter-clojure/blob/v1.1.1/lib/init.coffee#L22-L28) of code the command that gets executed is built up. First either `java` or the contents of `javaExecutablePath` is used as the command base. The the parameters get assembled. By default it looks like it runs something similar to this:

```ShellSession
java -jar /path/to/closure-1.7.0.jar -i /path/to/file_currently_open.ext
```

So if you manually run a command like that on a ClojurScript file and get reasonable output, ClojustScript should work if it is added to the list of `grammarScopes` for this plugin.

Having said all that, now that I've checked while writing that up I see that it _should_ already be working since `source.clojurescript` is in the list of allowed grammars, do you have an example file where it isn't working? What do you get when you run `Editor: Log Cursor Scope` (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Alt</kbd> + <kbd>P</kbd>) on a ClosureScript file?

**Comment by damassi** [comment]
Thanks for working through this :) 

When I run log cursor scope this is what's returned:
```
Scopes at Cursor
source.clojure
meta.expression.clojure
meta.definition.global.clojure
meta.expression.clojure
meta.expression.clojure
meta.expression.clojure
meta.expression.clojure
```
And here's an example of a basic linting error:
 
<img width="517" alt="screen shot 2015-12-28 at 3 20 26 pm" src="https://cloud.githubusercontent.com/assets/236943/12027123/fcddb104-ad76-11e5-970f-73fa12f4312b.png">

**Comment by Arcanemagus** [comment]
Looks like it's working properly already then :stuck_out_tongue:

Were you expecting something that it isn't doing, or had you just not tried it yet?

**Comment by damassi** [comment]
Well what I mean about supporting ClojureScript is `js->clj` shouldn't be unresolved (its a common built in function in the global js namespace), and neither should `defproject` -- unless I am misunderstanding something?

**Comment by Arcanemagus** [comment]
You'll have to ask somebody familiar with ClojureScript for that, @trevershick?

**Comment by Arcanemagus** [comment]
Marking this as closed since linter-clojure is already running on ClojureScript files, feel free to continue the discussion though :wink:.

**Comment by damassi** [comment]
Sounds good. @trevershick, any help would be appreciated. I know there is a `cljs.jar` file that is used to compile ClojureScript; wondering if we could leverage that somehow within the library along with the typical `clojure.jar` that is used for linting.

**Comment by Arcanemagus** [comment]
Just to be clear, I have no experience with Clojure beyond knowing it's a language. If there are actual implementation details that need changing to get proper support in by all means please reopen this issue.

**Comment by damassi** [comment]
I'm assuming there is, but I honestly have no clue what they could be (total noob here). Whatever it is I imagine its trivial, though, as there are linters available for other editors.

**Comment by trevershick** [comment]
I'll take a look. I've been ill lately but i'll look after the new year.
