### ISSUE TITLE
Install `linter` automatically.

### ISSUE THREAD

**Issue by kepler0** [AtomLinter/linter-clojure#7]
By using [`atom-package-deps`](https://github.com/steelbrain/package-deps) you are able to install `linter` automatically on activation. This will allow new Atom users to install only your package and nothing else, removing one step from the installation process.

Please see AtomLinter/linter-ruby#38 for example.

**Comment by dvcrn** [comment]
Can we strip this out again or make it optional? There are cases where you want more granular control over your packages and packages installing packages makes this very tiresome. 

Nuclide users for example use the `nuclide-diagnostics` package which conflicts with linter and disables it.

**Comment by Arcanemagus** [comment]
@dvcrn This use case has already been handled. The `linter` package will be installed if it isn't already... but if you have it installed but disabled it will not be re-enabled. So simply disable `linter` and keep on using `nuclide-diagnostics`.

Until Atom implements [service dependencies](https://github.com/atom/apm/pull/387) this is unfortunately the best that we can do without relying on every user to install `linter` themselves.

Marking this as closed as this has been implemented in #11.

**Comment by dvcrn** [comment]
To clear up, we had a very specific usecase over at proton - https://github.com/dvcrn/proton/issues/50. Proton orchestrates package installations for you. The problem was that when a sub-packge (we call them 'layers') implements linter support even though the user didn't enable the `linter` layer, `linter-clojure` (and friends) would just pull `linter` in. On next atom start, proton would see that `linter` is installed without it being orchestrated through proton and proceeds to remove it. Then `linter-clojure` installs it in again and so on. 

We went with lazy-loading `linter-clojure`. If `linter` is not installed, `linter-clojure` will not be installed either so it can't hard install `linter` automatically later on.

**Comment by Arcanemagus** [comment]
Just finished reading through that issue, looks like an interesting and quite complex project.

@steelbrain is currently [working on](https://github.com/atom-community/linter/pull/995) splitting the UI out into a separate package that integrates via a service with linter. Once that is complete you guys may be interested in building your own UI to better integrate into the changes you are making.

It looks like you guys are basically implementing a workaround for exactly what the service dependencies PR on atom/apm that I linked above is meant to solve. Once that gets completed a _lot_ of these issues can be solved relatively simply but for now unfortunately we are stuck with this situation.
